security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
            login:
                pattern:  ^/api/login
                stateless: true
                anonymous: true
                form_login:
                    check_path:               /api/login_check
                    success_handler:          lexik_jwt_authentication.handler.authentication_success
                    failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                    require_previous_session: false
           
            api:
                pattern:   ^/api
                stateless: true
                lexik_jwt:
                    authorization_header: # check token in Authorization Header
                        enabled: true
                        prefix:  Bearer
          
                    query_parameter:      # check token in query string parameter
                        enabled: true
                        name:    token
                    throw_exceptions:        false     # When an authentication failure occurs, return a 401 response immediately
                    create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response
                  
                    
                

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        