main_api:
    resource: SMP3Bundle\Controller\LibraryController 
    type: rest


playlist:
    type: rest
    resource: SMP3Bundle\Controller\PlaylistController
    
users:
    type: rest
    resource: SMP3Bundle\Controller\UserController