#TODO: don't pass container to services
services:
    smp3.fileinfo:
        class: SMP3Bundle\Service\FileInfoService
        arguments: [] 
    smp3.library:
        class: SMP3Bundle\Service\LibraryService
        arguments: ['@service_container']
    smp3.config:
        class: SMP3Bundle\Service\ConfigService
        arguments:
            - %discoverable_exts%
        
