services:
    smp3.fileinfo:
        class: SMP3Bundle\Service\FileInfoService
        arguments: [] 
    smp3.library:
        class: SMP3Bundle\Service\LibraryService
        arguments: ['@service_container']
    
