services:
    smp3.fileinfo:
        class: SMP3Bundle\Service\FileInfoService
        arguments: [] 
    smp3.library:
        class: SMP3Bundle\Service\LibraryService
        arguments: 
            - '@doctrine'
            - '@smp3.fileinfo'
            - '@smp3.config'
    smp3.config:
        class: SMP3Bundle\Service\ConfigService
        arguments:
            - %discoverable_exts%
        
