services:
    smp3.checksum:
        class: SMP3Bundle\Service\ChecksumService
    
    smp3.fileinfo:
        class: SMP3Bundle\Service\FileInfoService
        arguments: [] 
    
    smp3.library:
        class: SMP3Bundle\Service\LibraryService
        arguments: 
            - '@doctrine'
            - '@smp3.fileinfo'
            - '@smp3.config'
            - '@smp3.checksum'
    
    smp3.config:
        class: SMP3Bundle\Service\ConfigService
        arguments:
            - %discoverable_exts%
    
    smp3.playlist:
        class: SMP3Bundle\Service\PlaylistService
        arguments:
            - '@doctrine'
            - '@security.token_storage'
    
    smp3.ytfetch:
        class: SMP3Bundle\Service\YTService
        arguments:
            - '%google_apikey%'
    
    smp3.transcode:
        class: SMP3Bundle\Service\TranscodeService
    
    smp3.consumer.fetch:
        class: SMP3Bundle\Service\Consumer\Fetch
        arguments:
            - '@doctrine'
            - '@smp3.ytfetch'
            - '@smp3.library'
            - '@smp3.transcode'
    
    smp3.consumer.discover:
        class: SMP3Bundle\Service\Consumer\Discover
        arguments: 
            - '@doctrine'
            - '@smp3.library'